name: QA Tests

on: pull_request

jobs:
  setup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Install serve
        run: npm install -g serve
      - name: Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          retention-days: 1
          path: builds/${{ github.event.pull_request.head.sha }}/build

  cypress-tests:
    runs-on: ubuntu-latest
    needs: setup-build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: builds/${{ github.event.pull_request.head.sha }}/build
      - name: Serve
        run: serve -s build > /dev/null 2>&1 &
      - name: Echo app
        run: |
          sudo apt-get update; sudo apt-get install -y curl
          curl http://localhost:3000
