name: QA Tests

on: pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Install serve
        run: npm install -g serve
      - name: Build
        run: npm run build
      - name: Serve
        run: serve -s build > /dev/null 2>&1 &
      - name: Echo app
        run: |
          apt-get update; apt-get install -y curl
          curl http://localhost:3000
